### ISSUE TITLE
Doesn’t work for iPhone 12 Pro Max iOS 14.4.1

### ISSUE THREAD

**Issue by jaybo626** [WilsontheWolf/WebShade#10]
Doesn't work for iOS 14.4.1

**Comment by WilsontheWolf** [comment]
It works on my iPad Air 4 (which has the same chip as the 12 pro max) on 14.5 so it should work for you. 

Can you tell me:
Which websites you tried
Is dark mode turned on your phone?

**Comment by WilsontheWolf** [comment]
Closing due to lack of update. If you're still experiencing issues let me know.
