### ISSUE TITLE
bug: it doesn't only inject in safari

### ISSUE THREAD

**Issue by 3m4r5** [WilsontheWolf/WebShade#11]
is it possible to add a feature that manually lets you pick which browsers/apps to inject into?

because currently it injects into every app like github and MyAnimeList.

it's possible to disable it using choicy but I think it would be better if it didn't try to inject in those apps from the get-go instead of being blocked by choicy.

**Comment by WilsontheWolf** [comment]
This is not a bug. This is due to design, as that way it works, it need to inject into every app so external browsers (chrome, firefox, brave, etc.) work. As for now I don't plan on adding an app whitelist. Choicy or libhooker configurator are recommended.

**Comment by 3m4r5** [comment]
okay 👍
thank you for this amazing tweak.
