### ISSUE TITLE
WebShade hiding black pieces in chess apps and websites

### ISSUE THREAD

**Issue by kernelle** [WilsontheWolf/WebShade#3]
Noticed WebShade has the side-effect that it also removes the black pieces from any chess websites and apps. 

![BDAFDE7C-4BDB-4577-A396-D0838FB4E67A](https://user-images.githubusercontent.com/10882903/111909413-7b4a7180-8a5d-11eb-886a-be21c5a015e0.jpeg)

[Link to lichess example site](https://lichess.org/analysis/4rk2/1p1RnBbR/6p1/2B1P1N1/p4P2/P7/1Pp3P1/2K5_w_-_-_0_1) 

I understand the program is working as expected, however I still feel like a blacklist settings is evident.

**Comment by WilsontheWolf** [comment]
Hello there.

A blacklist setting would be a lot of work and to be honest with you I don't want to go through with that. 
You can however try these;
If your chess app is its own app (which the screenshot seems to suggest it is) disable the tweak injecting into your app via choicy.
If your chess game is part of a website you can disable light mode on your phone which should return the chess site back to its previous state. 

If you (or anyone really) wanted to make a pr to add preferences I wouldn't be opposed to merging it. However, I don't really want to go through the effort myself. Sorry

**Comment by kernelle** [comment]
Completely understandable, thank you for your work, candor, and your suggestion. I'll definitely be looking into Choicy.
