### ISSUE TITLE
WebShade makes WeChat show a blank black screen in chatting page

### ISSUE THREAD

**Issue by the-eric-kwok** [WilsontheWolf/WebShade#6]
The first image is normal chatting page and the second one is the blank black screen. 
![IMG_1656](https://user-images.githubusercontent.com/16463312/119518916-8b5b3600-bdab-11eb-81e1-b58c8b7cc20c.PNG)
![IMG_1657](https://user-images.githubusercontent.com/16463312/119521866-1b01e400-bdae-11eb-86d4-445201ee745a.PNG)

When I first launch WeChat the chat page loads normally and if I go to Home Screen and go into WeChat again, in the chatting page it shows the blank black screen. And even if I disable WebShade in Choicy and relaunch WeChat, it will still give me a blank black screen in chatting page. 

The screen recoding is attached below.
[RPReplay_Final1621953405.mov.zip](https://github.com/WilsontheWolf/WebShade/files/6540232/RPReplay_Final1621953405.mov.zip)

For more info:
1. if I disable WeChatPure (repo: https://repo.initnil.com) and WebShade together and launch WeChat again it will become completely normal
2. if I [enable WebShade & disable WeChatPure] or [enable WeChatPure and disable WebShade] the blank black screen issue appears. 
3. If I uninstall WeChatPure and enable WebShade in Choicy the blank black screen issue appears. 
4. If I uninstall WebShade and enable WeChatPure it will become normal.
5. If I disable WebShade only with iCleaner Pro globally it will be normal.
6. If I disable WeChatPure and enable WebShade with iCleaner Pro globally the blank black screen issue appears. 

~~And this issue doesn't exist on Taurine.~~ So I'm confused and not sure is it a conflict between WeChatPure and WebShade or Choicy?

Device: iPhone 12 mini
OS: iOS 14.3
Jailbreak: unc0ver 6.1.2 with Substitute 2.1.0
Tweaks list: 
[文本-76A17043367C-1.txt](https://github.com/WilsontheWolf/WebShade/files/6540447/-76A17043367C-1.txt)

I will test it again on Taurine.
[Edit] this issue appears on Taurine 1.0.4 with libhooker 1.6.0 as well.

**Comment by WilsontheWolf** [comment]
Hey! I might have possible fixed this in a new build. Could you test this out for me? https://cdn.discordapp.com/attachments/718406334567153734/951301992771383296/com.wilsonthewolf.webshade_0.0.3-beta2.deb Thanks!

**Comment by the-eric-kwok** [comment]
I updated it to 0.0.3 and WeChat is not effective now, good job!
