### ISSUE TITLE
WebShade breaks mega.nz website

### ISSUE THREAD

**Issue by AymenKcm1** [WilsontheWolf/WebShade#8]
**WebShade: OFF**

![image](https://user-images.githubusercontent.com/67245917/122125482-71e85f80-ce28-11eb-983b-1a7f93158794.jpeg)

**WebShade: ON**

![image](https://user-images.githubusercontent.com/67245917/122125546-83ca0280-ce28-11eb-8ca7-a44337410d6a.jpeg)

**Comment by WilsontheWolf** [comment]
Hey!

I've been experimenting with stuff. I got a test build with preferences. Install it here https://cdn.discordapp.com/attachments/718406334567153734/951301992771383296/com.wilsonthewolf.webshade_0.0.3-beta2.deb
You should be able to add a custom rule by going to site settings adding a new site naming what you want and adding `mega.` (as mega has several domains) to the website match field. Then switch the engine to basic (or off). The basic engine interferes less and as such is more compatible. 
![9A2A7660-970A-46F6-AB29-E52317908A60](https://user-images.githubusercontent.com/33164598/157579225-c44e83dd-ea20-4bb2-ad80-f00ee9d0c31e.png)

Here is the advanced (old) engine
![30672679-B422-4326-ADCC-8D5A5675B85E](https://user-images.githubusercontent.com/33164598/157579047-292c4920-d397-4c8a-929e-18e54137a0b8.png)
And here is the basic (new) engine 
![ED7DBCB5-E7FB-426C-9FE7-A99408DCF27C](https://user-images.githubusercontent.com/33164598/157579131-00cf9a5f-a255-4f43-8e0d-21f49ccc91f6.png)

**Comment by AymenKcm1** [comment]
Thanks, it's working great 👍
